# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbName', models.CharField(db_column='db_name', help_text='请输入数据库名!', max_length=128, verbose_name='数据库名')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间!', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间!', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库',
                'db_table': 'cmdb_db_database',
            },
        ),
        migrations.CreateModel(
            name='dbInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceName', models.CharField(db_column='instance_name', help_text='请输入实例名!', max_length=128, verbose_name='实例名')),
                ('instanceType', models.CharField(choices=[('MYSQL', 'MYSQL'), ('REDIS', 'REDIS'), ('ORACLE', 'ORACLE'), ('MONGO', 'MONGO')], db_column='instance_type', help_text='请输入实例类型!', max_length=32, verbose_name='实例类型')),
                ('portNum', models.IntegerField(db_column='port_num', help_text='请输入实例端口号!', verbose_name='实例端口号')),
                ('instanceRole', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MASTER', 'MASTER'), ('SLAVE', 'SLAVE')], db_column='instance_role', default='MASTER', help_text='请输入实例角色!', max_length=32, verbose_name='实例角色')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间!', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间!', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '数据库实例',
                'verbose_name_plural': '数据库实例',
                'db_table': 'cmdb_db_instance',
            },
        ),
        migrations.CreateModel(
            name='dbPrivilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privName', models.CharField(db_column='priv_name', help_text='请输入权限名!', max_length=64, verbose_name='权限名')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间!', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间!', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '数据库权限',
                'verbose_name_plural': '数据库权限',
                'db_table': 'cmdb_db_privs',
            },
        ),
        migrations.CreateModel(
            name='dbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(db_column='user_name', help_text='请输入用户名!', max_length=128, verbose_name='用户名')),
                ('userPasswd', models.CharField(db_column='user_passwd', help_text='请输入密码!', max_length=128, verbose_name='密码')),
                ('userType', models.CharField(choices=[('WEB', 'WEB'), ('ADMIN', 'ADMIN'), ('SYS', 'SYS'), ('READ', 'READ'), ('BACKUP', 'BACKUP'), ('GENERAL', 'GENERAL'), ('MONITOR', 'MONITOR'), ('REPLICATION', 'REPLICATION'), ('INCEPTION', 'INCEPTION'), ('BIGDATA', 'BIGDATA')], db_column='user_type', help_text='请输入用户类型!', max_length=64, verbose_name='用户类型')),
                ('ipRange', models.CharField(db_column='ip_range', help_text='请输入IP范围!', max_length=32, verbose_name='IP范围')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间!', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间!', null=True, verbose_name='记录最后更新时间')),
                ('dbRange', models.ManyToManyField(to='cmdb.dbDatabase')),
                ('instance', models.ForeignKey(db_column='instance', db_index=False, help_text='请选择实例！', on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.dbInstance', verbose_name='实例名')),
                ('userPriv', models.ManyToManyField(to='cmdb.dbPrivilege')),
            ],
            options={
                'verbose_name': '数据库用户',
                'verbose_name_plural': '数据库用户',
                'db_table': 'cmdb_db_user',
            },
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(db_column='business_name', help_text='请输入业务线名称!', max_length=32, verbose_name='业务线名称')),
                ('serviceEnv', models.CharField(choices=[('QA', 'QA'), ('DEV', 'DEV'), ('PRD', 'PRD'), ('PRE_PRD', 'PRE_PRD')], db_column='service_env', default='PRD', help_text='请输入服务器环境!', max_length=32, verbose_name='服务器环境')),
                ('hostName', models.CharField(db_column='host_name', help_text='请输入主机名!', max_length=64, verbose_name='主机名')),
                ('intranetIpAddr', models.GenericIPAddressField(db_column='intranet_ip_addr', help_text='请输入内网IP地址!', verbose_name='内网IP地址')),
                ('publicIpAddr', models.GenericIPAddressField(db_column='public_ip_addr', help_text='请输入公网IP地址!', verbose_name='公网IP地址')),
                ('sshPort', models.CharField(db_column='ssh_port', help_text='请输入SSH端口号!', max_length=8, verbose_name='SSH端口号')),
                ('hostType', models.CharField(choices=[('DB', 'DB'), ('WEB', 'WEB'), ('REDIS', 'REDIS'), ('NGINX', 'NGINX')], db_column='host_type', default='WEB', help_text='请输入服务器角色!', max_length=32, verbose_name='服务器角色')),
                ('hostRole', models.CharField(choices=[('GENERAL', 'GENERAL'), ('MASTER', 'MASTER'), ('SLAVE', 'SLAVE')], db_column='host_role', default='GENERAL', help_text='请输入服务器环境!', max_length=32, verbose_name='服务器环境')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
                'db_table': 'cmdb_host',
            },
        ),
        migrations.CreateModel(
            name='hostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostUser', models.CharField(db_column='host_user', help_text='请输入操作系统用户!', max_length=64, verbose_name='操作系统用户')),
                ('hostPasswd', models.CharField(db_column='host_passwd', help_text='请输入操作系统密码!', max_length=300, verbose_name='操作系统密码')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
                ('host', models.ForeignKey(db_column='host', db_index=False, help_text='请选择主机', on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.host', verbose_name='内网IP')),
            ],
            options={
                'verbose_name': '机器用户密码',
                'verbose_name_plural': '机器用户密码',
                'db_table': 'cmdb_host_user',
            },
        ),
        migrations.AddField(
            model_name='dbinstance',
            name='host',
            field=models.ForeignKey(db_column='host', db_index=False, help_text='请选择主机', on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.host', verbose_name='内网IP'),
        ),
        migrations.AddField(
            model_name='dbdatabase',
            name='instance',
            field=models.ForeignKey(db_column='instance', db_index=False, help_text='请选择实例！', on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.dbInstance', verbose_name='实例名'),
        ),
    ]
