# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgroup',
            name='groupEnv',
            field=models.CharField(choices=[('QA', 'QA'), ('DEV', 'DEV'), ('PRD', 'PRD'), ('PRE_PRD', 'PRE_PRD')], db_column='group_env', default='PRD', help_text='请输入数据库组环境!', max_length=32, verbose_name='数据库组环境'),
        ),
    ]
