# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_dbgroup_groupenv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbgroup',
            name='clusterName',
        ),
        migrations.AddField(
            model_name='dbgroup',
            name='businessName',
            field=models.CharField(db_column='business_name', default='', help_text='请输入业务线名称!', max_length=32, verbose_name='业务线名称'),
        ),
    ]
