# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171221_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbinstance',
            name='instanceStatus',
            field=models.CharField(choices=[('正常运行', '正常运行'), ('已下线', '已下线'), ('上线中', '上线中'), ('计划维护中', '计划维护中'), ('故障维护中', '故障维护中')], db_column='instance_status', default='正常运行', help_text='请选择实例状态!', max_length=32, verbose_name='实例状态'),
        ),
    ]
