# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('main_host', models.CharField(max_length=200, verbose_name='主库地址')),
                ('main_port', models.IntegerField(default=3306, verbose_name='主库端口')),
                ('main_user', models.CharField(max_length=100, verbose_name='登录主库的用户名')),
                ('main_password', models.CharField(max_length=300, verbose_name='登录主库的密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主库地址',
                'verbose_name_plural': '主库地址',
            },
        ),
        migrations.CreateModel(
            name='sql_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=128, verbose_name='工单内容')),
                ('engineer', models.CharField(max_length=50, verbose_name='发起人')),
                ('review_man', models.CharField(max_length=50, verbose_name='审核人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('已正常结束', '已正常结束'), ('人工终止流程', '人工终止流程'), ('自动审核中', '自动审核中'), ('等待审核人审核', '等待审核人审核'), ('执行中', '执行中'), ('自动审核不通过', '自动审核不通过'), ('执行有异常', '执行有异常')], max_length=50)),
                ('is_backup', models.CharField(choices=[('否', '否'), ('是', '是')], max_length=20, verbose_name='是否备份')),
                ('review_content', models.TextField(verbose_name='自动审核内容的JSON格式')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('reviewok_time', models.DateTimeField(blank=True, null=True, verbose_name='人工审核通过的时间')),
                ('sql_content', models.TextField(verbose_name='具体sql内容')),
                ('execute_result', models.TextField(verbose_name='执行结果的JSON格式')),
            ],
            options={
                'verbose_name': '工单管理',
                'verbose_name_plural': '工单管理',
            },
        ),
    ]
